### ISSUE TITLE
Update version?

### ISSUE THREAD

**Issue by pgerundt** [contao-components/tablesorter#1]
First time I had to take a deeper look at the tablesorter component. The mission was to sort a column by date format dd.mm.yyyy
Unfortunately the version 2.0.5 is based on jQuery's metadata plugin - which is deprecated since jQuery 1.4.3.
So the component should be updated to 2.31.1 which is perfectly downward compatibel.

I just replaced jquery.tablesorter.min.js and theme.default.css and now a lot of additional features are available.

**Comment by leofeyer** [comment]
I assume you are talking about this fork? https://github.com/Mottie/tablesorter

**Comment by pgerundt** [comment]
This is correct. I couldn't fiund any higher version of Christian Bach's original plugin. The website http://tablesorter.com is down and the plugin seems to be abandoned since 2015.
